deseret_from_weird_chars = {
    'Ä': '𐐀', '¥': '𐐨',  # LONG I (i as in machine)
    'Å': '𐐁', '∂': '𐐩',  # LONG E (e as in grey)
    'Ç': '𐐂', '∑': '𐐪',  # LONG A (a as in art)
    'É': '𐐃', '∏': '𐐫',  # LONG AH (au as in aught)
    'Ñ': '𐐄', 'π': '𐐬',  # LONG O (o as in tone)
    'Ö': '𐐅', '∫': '𐐭',  # LONG OO (oo as in moo)
    'Ü': '𐐆', 'ª': '𐐮',  # SHORT I (i as in it)
    'á': '𐐇', 'º': '𐐯',  # SHORT E (e as in desert)
    'à': '𐐈', 'Ω': '𐐰',  # SHORT A (a as in cat)
    'â': '𐐉', 'æ': '𐐱',  # SHORT AH (o as in cot)
    'ä': '𐐊', 'ø': '𐐲',  # SHORT O (o as in woman)
    'ã': '𐐋', '¿': '𐐳',  # SHORT OO (oo as in book)
    'å': '𐐌', '¡': '𐐴',  # AY (the sound of the pronoun I)
    'ç': '𐐍', 'À': '𐐵',  # OW (ow as in cow)
    'é': '𐐎', 'Ã': '𐐶',  # WU (w as in wonder)
    'è': '𐐏', 'Õ': '𐐷',  # YEE (y as in you)
    'ê': '𐐐', 'Œ': '𐐸',  # H (h as in hurrah)
    'ë': '𐐑', 'œ': '𐐹',  # PEE (p as in put)
    'í': '𐐒', 'ÿ': '𐐺',  # BEE (b as in bee)
    'ì': '𐐓', 'Ÿ': '𐐻',  # TEE (t as in teach)
    'î': '𐐔', 'ﬁ': '𐐼',  # DEE (d as in Deseret)
    'ï': '𐐕', 'ﬂ': '𐐽',  # CHEE (ch as in cheese)
    'ñ': '𐐖', 'Â': '𐐾',  # JEE (j as in John)
    'ó': '𐐗', 'Ê': '𐐿',  # KAY (k as in kitten)
    'ò': '𐐘', 'Á': '𐑀',  # GAY (g as in good)
    'ô': '𐐙', 'Ë': '𐑁',  # EF (f as in France)
    'ö': '𐐚', 'È': '𐑂',  # VEE (v as in voice)
    'õ': '𐐛', 'Í': '𐑃',  # ETH (unvoiced th as in think)
    'ú': '𐐜', 'Î': '𐑄',  # THEE (voiced th as in they)
    'ù': '𐐝', 'Ï': '𐑅',  # ES (s as in said)
    'û': '𐐞', 'Ì': '𐑆',  # ZEE (z as in zebra)
    'ü': '𐐟', 'Ó': '𐑇',  # ESH (sh as in shoot)
    '¢': '𐐠', 'Ô': '𐑈',  # ZHEE (as in measure)
    'ß': '𐐡', 'Ò': '𐑉',  # ER (r as in ride)
    '´': '𐐢', 'Ú': '𐑊',  # EL (l as in letter)
    '¨': '𐐣', 'Û': '𐑋',  # EM (m as in Macintosh)
    'Æ': '𐐤', 'Ù': '𐑌',  # EN (n as in nice)
    'Ø': '𐐥', 'ı': '𐑍',  # ENG (ng as in sing)
}

phonemes = {
    '𐐀': 'IE', '𐐨': 'ie',  # LONG I (i as in machine)
    '𐐁': 'EY', '𐐩': 'ey',  # LONG E (e as in grey)
    '𐐂': 'AA', '𐐪': 'aa',  # LONG A (a as in art)
    '𐐃': 'AU', '𐐫': 'au',  # LONG AH (au as in aught)
    '𐐄': 'OA', '𐐬': 'oa',  # LONG O (o as in tone)
    '𐐅': 'OO', '𐐭': 'oo',  # LONG OO (oo as in moo)
    '𐐆': 'I', '𐐮': 'i',  # SHORT I (i as in it)
    '𐐇': 'E', '𐐯': 'e',  # SHORT E (e as in desert)
    '𐐈': 'A', '𐐰': 'a',  # SHORT A (a as in cat)
    '𐐉': 'O', '𐐱': 'o',  # SHORT AH (o as in cot)
    '𐐊': 'O', '𐐲': 'o',  # SHORT O (o as in woman)
    '𐐋': 'U', '𐐳': 'u',  # SHORT OO (oo as in book)
    '𐐌': 'I', '𐐴': 'i',  # AY (the sound of the pronoun I)
    '𐐍': 'OW', '𐐵': 'ow',  # OW (ow as in cow)
    '𐐎': 'W', '𐐶': 'w',  # WU (w as in wonder)
    '𐐏': 'Y', '𐐷': 'y',  # YEE (y as in you)
    '𐐐': 'H', '𐐸': 'h',  # H (h as in hurrah)
    '𐐑': 'P', '𐐹': 'p',  # PEE (p as in put)
    '𐐒': 'B', '𐐺': 'b',  # BEE (b as in bee)
    '𐐓': 'T', '𐐻': 't',  # TEE (t as in teach)
    '𐐔': 'D', '𐐼': 'd',  # DEE (d as in Deseret)
    '𐐕': 'CH', '𐐽': 'ch',  # CHEE (ch as in cheese)
    '𐐖': 'J', '𐐾': 'j',  # JEE (j as in John)
    '𐐗': 'K', '𐐿': 'k',  # KAY (k as in kitten)
    '𐐘': 'G', '𐑀': 'g',  # GAY (g as in good)
    '𐐙': 'F', '𐑁': 'f',  # EF (f as in France)
    '𐐚': 'V', '𐑂': 'v',  # VEE (v as in voice)
    '𐐛': 'TH', '𐑃': 'th',  # ETH (unvoiced th as in think)
    '𐐜': 'TH', '𐑄': 'TH',  # THEE (voiced th as in they)
    '𐐝': 'S', '𐑅': 's',  # ES (s as in said)
    '𐐞': 'Z', '𐑆': 'z',  # ZEE (z as in zebra)
    '𐐟': 'SH', '𐑇': 'sh',  # ESH (sh as in shoot)
    '𐐠': 'z', '𐑈': 'z',  # ZHEE (as in measure)
    '𐐡': 'R', '𐑉': 'r',  # ER (r as in ride)
    '𐐢': 'L', '𐑊': 'l',  # EL (l as in letter)
    '𐐣': 'M', '𐑋': 'm',  # EM (m as in Macintosh)
    '𐐤': 'N', '𐑌': 'n',  # EN (n as in nice)
    '𐐥': 'NG', '𐑍': 'ng',  # ENG (ng as in sing)
}
